

### driver registration
POST http://localhost:8888/api/driver HTTP/1.1
Content-Type:application/json

{
    "email":"test@gmail.com",
    "firstName":"",
    "lastName":"kidus",
    "licenseNo":"1234",
    "licenceGrade":"pub 1",
    "phone":"0302320",
    "gender":"male",
    "salary":"1242",
    "age":"20"
}

# GET ALL REQUESTS
###
GET http://localhost:8888/api/driver

# GET driver by ID
###
GET http://localhost:8888/api/driver/1

# update driver by ID
###
put http://localhost:8888/api/driver/1
Content-Type: application/json

{
    "email":"test1@gmail.com",
    "firstName":"meresa",
    "lastName":"kidus"
 
}