### order registration
POST http://localhost:8888/api/orders/ HTTP/1.1
Content-Type:application/json

{  
   "customer_id" :1 , 
   "user_id":1, 
   "car_id":1, 
   "request_id":1
}


#### GET ALL ORDERD 

GET http://localhost:8888/api/orders/
