# FROM authController
# REGISTER USER (WITH OUT ADDRESS)
###
POST http://localhost:8888/api/auth/register HTTP/1.1
Content-Type:application/json

{  
    "first_name": "kidus",
    "last_name": "meresa",
    "password":"123456Mere",
    "username":"meresa"
}

# FROM usersController
# GET ALL USERS
###
GET http://localhost:8888/api/users/ HTTP/1.1

# GET USER BY ID
###
GET http://localhost:8888/api/users/4 HTTP/1.1


# UPDATE USER 
###
PUT http://localhost:8888/api/users/4 HTTP/1.1
Content-Type:application/json

{  
    "first_name": "Kidus",
    "last_name": "Meresa"
}

# DELETE USER BY ID
###
DELETE  http://localhost:8888/api/users/3 HTTP/1.1

# ========================================================================================